language: python
python:
  - "3.5"

install: "pip install -r requirements.txt"

env:
- DATABASE_URL=postgres:///testing
- SENDGRID_USERNAME=testing
- SENDGRID_PASSWORD=testing

script: python manage.py test --settings=nferoot.settings.travis